id: P006896
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 12:29:22.003795
source_metadata:
  id: bdr:W1KG25593
  title: བོད་ཀྱི་དགོན་སྡེ་གྲགས་ཅན།
  author: ''
  volumes:
    48667aadd99f494c8d91891c1ae9b74a:
      image_group_id: I1KG25595
      title: ''
      volume_number: 1
      total_pages: 246
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
